LIBRARY := TruthNtupleLooper
OBJDIR  := $(PWD)/obj
SRCDIR  := $(PWD)/src
INCDIR  := $(PWD)/include
EXECUTABLE := $(PWD)/NtupleLooper

LOCAL_LIBS_PATH += $(SH_LIB_PATH)/libProgressBar.so

INCLUDES += -I../
INCLUDES += -I./
INCLUDES += -I../../

include $(PWD)/../Makefile.common
