LIBRARY := TruthNtupleLooper
OBJDIR  := $(PWD)/obj
SRCDIR  := $(PWD)/src
INCDIR  := $(PWD)/include
EXECUTABLE := $(PWD)/TruhtNtupleLooper

LOCAL_LIBS_PATH += $(SH_LIB_PATH)/libProgressBar.so
LOCAL_LIBS_PATH += $(SH_LIB_PATH)/libTruthRecordHelpers.so

INCLUDES += -I../
INCLUDES += -I./
INCLUDES += -I../../

include $(PWD)/../Makefile.common
