- label: 'x=0.50'
  color: 600 # kBlue
  shape: 20
  line: 1
  x_label: 'm(#chi_{1}^{#pm}) [GeV]'
  x_max:   600
  files:
    - x_value: 75
      file: '/tmp/bjackson/truth_ntuples/c1n2_75.n1_50.0.xslep_0.5.truth.root'
    - x_value: 100
      file: '/tmp/bjackson/truth_ntuples/c1n2_100.n1_50.0.xslep_0.5.truth.root'
    - x_value: 125
      file: '/tmp/bjackson/truth_ntuples/c1n2_125.n1_50.0.xslep_0.5.truth.root'
    - x_value: 150
      file: '/tmp/bjackson/truth_ntuples/c1n2_150.n1_50.0.xslep_0.5.truth.root'
    - x_value: 175
      file: '/tmp/bjackson/truth_ntuples/c1n2_175.n1_50.0.xslep_0.5.truth.root'
    - x_value: 200
      file: '/tmp/bjackson/truth_ntuples/c1n2_200.n1_50.0.xslep_0.5.truth.root'
    - x_value: 250
      file: '/tmp/bjackson/truth_ntuples/c1n2_250.n1_50.0.xslep_0.5.truth.root'
    - x_value: 300
      file: '/tmp/bjackson/truth_ntuples/c1n2_300.n1_50.0.xslep_0.5.truth.root'
    - x_value: 400
      file: '/tmp/bjackson/truth_ntuples/c1n2_400.n1_50.0.xslep_0.5.truth.root'
    - x_value: 500
      file: '/tmp/bjackson/truth_ntuples/c1n2_500.n1_50.0.xslep_0.5.truth.root'

- label: 'x=0.05'
  color: 851 # kAzure - 9
  shape: 23
  line: 1
# x_label: 'm(C1) [GeV]'
  x_label: 'm(#chi_{1}^{#pm}) [GeV]'
  x_max:   600
  files:
    - x_value: 75
      file: '/tmp/bjackson/truth_ntuples/c1n2_75.n1_50.0.xslep_0.05.truth.root'
    - x_value: 100
      file: '/tmp/bjackson/truth_ntuples/c1n2_100.n1_50.0.xslep_0.05.truth.root'
    - x_value: 125
      file: '/tmp/bjackson/truth_ntuples/c1n2_125.n1_50.0.xslep_0.05.truth.root'
    - x_value: 150
      file: '/tmp/bjackson/truth_ntuples/c1n2_150.n1_50.0.xslep_0.05.truth.root'
    - x_value: 175
      file: '/tmp/bjackson/truth_ntuples/c1n2_175.n1_50.0.xslep_0.05.truth.root'
    - x_value: 200
      file: '/tmp/bjackson/truth_ntuples/c1n2_200.n1_50.0.xslep_0.05.truth.root'
    - x_value: 250
      file: '/tmp/bjackson/truth_ntuples/c1n2_250.n1_50.0.xslep_0.05.truth.root'
    - x_value: 300
      file: '/tmp/bjackson/truth_ntuples/c1n2_300.n1_50.0.xslep_0.05.truth.root'
    - x_value: 400
      file: '/tmp/bjackson/truth_ntuples/c1n2_400.n1_50.0.xslep_0.05.truth.root'
    - x_value: 500
      file: '/tmp/bjackson/truth_ntuples/c1n2_500.n1_50.0.xslep_0.05.truth.root'

- label: 'x=0.95'
  color: 602 # kBlue + 2
  shape: 22
  line: 1
# x_label: 'm(C1) [GeV]'
  x_label: 'm(#chi_{1}^{#pm}) [GeV]'
  x_max:   600
  files:
    - x_value: 75
      file: '/tmp/bjackson/truth_ntuples/c1n2_75.n1_50.0.xslep_0.95.truth.root'
    - x_value: 100
      file: '/tmp/bjackson/truth_ntuples/c1n2_100.n1_50.0.xslep_0.95.truth.root'
    - x_value: 125
      file: '/tmp/bjackson/truth_ntuples/c1n2_125.n1_50.0.xslep_0.95.truth.root'
    - x_value: 150
      file: '/tmp/bjackson/truth_ntuples/c1n2_150.n1_50.0.xslep_0.95.truth.root'
    - x_value: 175
      file: '/tmp/bjackson/truth_ntuples/c1n2_175.n1_50.0.xslep_0.95.truth.root'
    - x_value: 200
      file: '/tmp/bjackson/truth_ntuples/c1n2_200.n1_50.0.xslep_0.95.truth.root'
    - x_value: 250
      file: '/tmp/bjackson/truth_ntuples/c1n2_250.n1_50.0.xslep_0.95.truth.root'
    - x_value: 300
      file: '/tmp/bjackson/truth_ntuples/c1n2_300.n1_50.0.xslep_0.95.truth.root'
    - x_value: 400
      file: '/tmp/bjackson/truth_ntuples/c1n2_400.n1_50.0.xslep_0.95.truth.root'
    - x_value: 500
      file: '/tmp/bjackson/truth_ntuples/c1n2_500.n1_50.0.xslep_0.95.truth.root'
