- label: 'm(#chi_{1}^{#pm} = 150 GeV :: m(#chi_{1}^{0} = 0 GeV'
  color: 851 # kAzure - 9
  shape: 22
  line: 1
  x_label: 'x_{slepton}'
  x_max:   1.0
  files:
    - x_value: 0.5
      file: '/tmp/bjackson/truth_ntuples/c1n2_150.n1_0.xslep_0.5.truth.root'
    - x_value: 0.6
      file: '/tmp/bjackson/truth_ntuples/c1n2_150.n1_0.xslep_0.6.truth.root'
    - x_value: 0.7
      file: '/tmp/bjackson/truth_ntuples/c1n2_150.n1_0.xslep_0.7.truth.root'
    - x_value: 0.8
      file: '/tmp/bjackson/truth_ntuples/c1n2_150.n1_0.xslep_0.8.truth.root'
    - x_value: 0.9
      file: '/tmp/bjackson/truth_ntuples/c1n2_150.n1_0.xslep_0.9.truth.root'

- label: 'm(#chi_{1}^{#pm} = 300 GeV :: m(#chi_{1}^{0} = 150 GeV'
  color: 600 # kBlue
  shape: 20
  line: 1
  x_label: 'x_{slepton}'
  x_max:   1.0
  files:
    - x_value: 0.5
      file: '/tmp/bjackson/truth_ntuples/c1n2_300.n1_150.xslep_0.5.truth.root'
    - x_value: 0.6
      file: '/tmp/bjackson/truth_ntuples/c1n2_300.n1_150.xslep_0.6.truth.root'
    - x_value: 0.7
      file: '/tmp/bjackson/truth_ntuples/c1n2_300.n1_150.xslep_0.7.truth.root'
    - x_value: 0.8
      file: '/tmp/bjackson/truth_ntuples/c1n2_300.n1_150.xslep_0.8.truth.root'
    - x_value: 0.9
      file: '/tmp/bjackson/truth_ntuples/c1n2_300.n1_150.xslep_0.9.truth.root'

- label: 'm(#chi_{1}^{#pm} = 400 GeV :: m(#chi_{1}^{0} = 150 GeV'
  color: 602 # kBlue + 2
  shape: 20
  line: 1
  x_label: 'x_{slepton}'
  x_max:   1.0
  files:
    - x_value: 0.5
      file: '/tmp/bjackson/truth_ntuples/c1n2_400.n1_0.xslep_0.5.truth.root'
    - x_value: 0.6
      file: '/tmp/bjackson/truth_ntuples/c1n2_400.n1_0.xslep_0.6.truth.root'
    - x_value: 0.7
      file: '/tmp/bjackson/truth_ntuples/c1n2_400.n1_0.xslep_0.7.truth.root'
    - x_value: 0.8
      file: '/tmp/bjackson/truth_ntuples/c1n2_400.n1_0.xslep_0.8.truth.root'
    - x_value: 0.9
      file: '/tmp/bjackson/truth_ntuples/c1n2_400.n1_0.xslep_0.9.truth.root'
