LIBRARY := HistogramHandlers
OBJDIR  := $(PWD)/obj
SRCDIR  := $(PWD)/src
INCDIR  := $(PWD)/include
# EXECUTABLE := $(PWD)/mt2

INCLUDES += -I../
INCLUDES += -I./
INCLUDES += -I../../

include $(PWD)/../Makefile.common
